version: '3.8'

services:
  # ─── Base de données PostgreSQL ───────────────────────────────
  postgres:
    image: postgres:15
    container_name: crypto_postgres
    environment:
      POSTGRES_DB: crypto_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"          # Port accessible sur ton PC
    volumes:
      - postgres_data:/var/lib/postgresql/data   # Sauvegarde les données
    restart: unless-stopped

  # ─── Zookeeper (nécessaire pour Kafka) ────────────────────────
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: crypto_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped

  # ─── Kafka (streaming) ────────────────────────────────────────
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: crypto_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped

volumes:
  postgres_data:


dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    depends_on:
      - postgres
      - kafka